oldfolder = cd ('../data/');
fprintf('%s\n', 'Training cascade detector.')
trainCascadeObjectDetector('detector.xml', ...
                     positiveInstances, 'neg/', ...
                     'NumCascadeStages',9,'FalseAlarmRate',0.005, ...
                     'FeatureType','LBP');
fprintf('%s\n', 'Done')
cd (oldfolder);